version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - my-network

  graphql-api:
    image: amirtalbi/whatsapp-api:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - my-network

  client: 
    image: amirtalbi/whatsapp-client:1.0.0
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - graphql-api
    environment:
      - GRAPHQL_API_URL=http://graphql-api:3000/graphql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge