version: '3.8'

services:
  redis:
    image: "redis:latest"
    networks:
      - my-network

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - my-network

networks:
  my-network:
    driver: bridge