name: Build

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "18"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build NestJS
  #       run: npm run build

  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $TOKEN | docker login -u amirtalbi --password-stdin

      - name: Build client image
        run: npm run docker:build:client

      - name: Build server image
        run: npm run docker:build:server

      - name: Publish client image
        run: npm run docker:publish:client

      - name: Publish server image
        run: npm run docker:publish:server
